import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/providers/auth-provider";
import { UserProvider } from "@/providers/users-providers";
import ConfigProvider from "antd/es/config-provider";
import ResilienceHeader from "@/components/header/Header";
import { SurvivorProvider } from "@/providers/survivors-provider";
import { LocationProvider } from "../providers/location-provider";
import { MedicalCentreProvider } from "@/providers/medicalCenter-provider";
import { PoliceStationProvider } from "@/providers/police-provider";
import { JournalEntryProvider } from "@/providers/journal-provider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const ReslienceColors = {
  token: {
    colorPrimary: "#38512f",
    colorPrimaryHover: "#8F997F",
    colorBgContainer: "#ffffff",
    colorBgTextHover: "#38512F",
    wireframe: false,
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConfigProvider theme={ReslienceColors}>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ResilienceHeader />
          <AuthProvider>
            <UserProvider>
              <LocationProvider>
                <MedicalCentreProvider>
                  <PoliceStationProvider>
                    <SurvivorProvider>
                      <JournalEntryProvider>{children}</JournalEntryProvider>
                    </SurvivorProvider>
                  </PoliceStationProvider>
                </MedicalCentreProvider>
              </LocationProvider>
            </UserProvider>
          </AuthProvider>
        </body>
      </html>
    </ConfigProvider>
  );
}
